name: Cross-platform Build and Release

env:
  ProductName: libhv

on:
  push:
    tags:
      - build_*

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install libssl-dev libnghttp2-dev

      - name: build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install -DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
          make -j$(nproc) VERBOSE=1
          make install

      - name: test
        run: |
          make check
          make run-unittest

  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          choco install -y openssl.light

      - name: build
        run: |
          mkdir cmake-build-win64
          cd cmake-build-win64
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build .

  build-apple:
    name: build-apple
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          ./configure
          make libhv evpp examples unittest

  build-android:
    name: build-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake git
          sudo apt install -y wget zip unzip tar

      - name: Install Android NDK
        run: |
          mkdir -p $HOME/android-sdk/ndk
          wget -q https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip -O ndk.zip
          unzip -q ndk.zip -d $HOME/android-sdk/ndk
          rm ndk.zip

      - name: Build dynamic library for Android
        run: |
          mkdir -p build-android
          cd build-android
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_NATIVE_API_LEVEL=21
          make
          zip -j libhv_android_arm64-v8a.zip libhv.so

      - name: Upload the .zip file as a release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build-android/libhv_android_arm64-v8a.zip
          asset_name: libhv_android_arm64-v8a.zip
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}
