name: Cross-platform Build and Release

env:
  ProductName: libhv

on:
  push:
    tags:
      - build_*

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update -y && sudo apt-get install -y build-essential cmake

      - name: Build dynamic library
        if: matrix.os != 'android-latest' && matrix.os != 'ios-latest'
        run: make && make install

      - name: Upload dynamic library
        if: matrix.os != 'android-latest' && matrix.os != 'ios-latest'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            /usr/local/lib/libhv.so # Update file name for Windows or MacOS if needed
            /usr/local/lib/libhv.dylib # Update file name for Linux or Windows if needed
            /usr/local/lib/libhv.dll # Update file name for Linux or MacOS if needed
          asset_name: libhv_${{ matrix.os }}_${{ matrix.arch }}.so # Update file extension for Windows or MacOS if needed
          asset_content_type: application/x-sharedlib
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dynamic library for Android
        if: matrix.os == 'ubuntu-latest'
        run: make android

      - name: Build dynamic library for iOS
        if: matrix.os == 'macos-latest'
        run: make ios

      - name: Create release
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'x64'
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: Automated release ${{ github.ref }}
          assets: |
            /usr/local/lib/libhv_linux_x64.so
            /usr/local/lib/libhv_macos_x64.dylib
            /usr/local/lib/libhv_windows_x64.dll
            /usr/local/lib/libhv_android_arm64-v8a.so
            /usr/local/lib/libhv_ios_arm64.so
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
